#!/usr/bin/env python3
"""
SARIF Parser for CodeQL Results
Extracts security findings from SARIF files generated by CodeQL analysis.
"""

import json
import glob
import sys
from typing import List, Dict, Any
from pathlib import Path


class SarifParser:
    """Parser for SARIF (Static Analysis Results Interchange Format) files."""
    
    def __init__(self, sarif_directory: str = "sarif-results"):
        self.sarif_directory = Path(sarif_directory)
        
    def parse_all_sarif_files(self) -> List[Dict[str, Any]]:
        """Parse all SARIF files in the directory and return consolidated results."""
        sarif_files = list(self.sarif_directory.glob("*.sarif"))
        
        if not sarif_files:
            print(f"No SARIF files found in {self.sarif_directory}")
            return []
        
        all_results = []
        for sarif_file in sarif_files:
            print(f"Parsing SARIF file: {sarif_file}")
            results = self.parse_sarif_file(sarif_file)
            all_results.extend(results)
        
        return all_results
    
    def parse_sarif_file(self, sarif_file: Path) -> List[Dict[str, Any]]:
        """Parse a single SARIF file and extract vulnerability information."""
        try:
            with open(sarif_file, 'r') as f:
                sarif_data = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"Error reading SARIF file {sarif_file}: {e}")
            return []
        
        results = []
        
        for run in sarif_data.get('runs', []):
            # Extract tool information
            tool_name = run.get('tool', {}).get('driver', {}).get('name', 'Unknown')
            tool_version = run.get('tool', {}).get('driver', {}).get('version', 'Unknown')
            
            # Process each result
            for result in run.get('results', []):
                parsed_result = self._parse_result(result, tool_name, tool_version)
                if parsed_result:
                    results.append(parsed_result)
        
        return results
    
    def _parse_result(self, result: Dict, tool_name: str, tool_version: str) -> Dict[str, Any]:
        """Parse a single result from the SARIF file."""
        rule_id = result.get('ruleId', 'unknown-rule')
        rule_index = result.get('ruleIndex', 0)
        
        # Get message
        message = self._get_message(result.get('message', {}))
        
        # Get severity level
        level = result.get('level', 'note')
        severity = self._map_severity(level)
        
        # Parse locations
        locations = self._parse_locations(result.get('locations', []))
        
        # Get rule metadata if available
        rule_metadata = self._get_rule_metadata(result, rule_index)
        
        return {
            'ruleId': rule_id,
            'severity': severity,
            'level': level,
            'message': message,
            'locations': locations,
            'tool': {
                'name': tool_name,
                'version': tool_version
            },
            'rule': rule_metadata
        }
    
    def _get_message(self, message_obj: Dict) -> str:
        """Extract message text from SARIF message object."""
        if isinstance(message_obj, str):
            return message_obj
        return message_obj.get('text', message_obj.get('markdown', 'No message'))
    
    def _map_severity(self, level: str) -> str:
        """Map SARIF level to common severity levels."""
        severity_mapping = {
            'error': 'high',
            'warning': 'medium', 
            'note': 'low',
            'info': 'informational'
        }
        return severity_mapping.get(level.lower(), 'unknown')
    
    def _parse_locations(self, locations: List[Dict]) -> List[Dict[str, Any]]:
        """Parse location information from SARIF results."""
        parsed_locations = []
        
        for location in locations:
            physical_location = location.get('physicalLocation', {})
            artifact_location = physical_location.get('artifactLocation', {})
            region = physical_location.get('region', {})
            
            parsed_location = {
                'file': artifact_location.get('uri', ''),
                'startLine': region.get('startLine', 0),
                'endLine': region.get('endLine', region.get('startLine', 0)),
                'startColumn': region.get('startColumn', 0),
                'endColumn': region.get('endColumn', region.get('startColumn', 0))
            }
            
            # Add snippet if available
            if 'snippet' in region:
                parsed_location['snippet'] = region['snippet'].get('text', '')
            
            parsed_locations.append(parsed_location)
        
        return parsed_locations
    
    def _get_rule_metadata(self, result: Dict, rule_index: int) -> Dict[str, Any]:
        """Extract rule metadata if available."""
        # This would require access to the rules array from the run
        # For now, return basic information
        return {
            'id': result.get('ruleId', ''),
            'index': rule_index,
            'helpUri': result.get('helpUri', ''),
        }
    
    def generate_summary(self, results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate a summary of the parsing results."""
        if not results:
            return {
                'total': 0,
                'by_severity': {},
                'by_rule': {},
                'files_affected': 0
            }
        
        # Count by severity
        severity_counts = {}
        rule_counts = {}
        affected_files = set()
        
        for result in results:
            severity = result['severity']
            rule_id = result['ruleId']
            
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
            rule_counts[rule_id] = rule_counts.get(rule_id, 0) + 1
            
            # Count affected files
            for location in result['locations']:
                if location['file']:
                    affected_files.add(location['file'])
        
        return {
            'total': len(results),
            'by_severity': severity_counts,
            'by_rule': rule_counts,
            'files_affected': len(affected_files),
            'affected_files': list(affected_files)
        }


def main():
    """Main function for command-line usage."""
    sarif_dir = sys.argv[1] if len(sys.argv) > 1 else "sarif-results"
    
    parser = SarifParser(sarif_dir)
    results = parser.parse_all_sarif_files()
    summary = parser.generate_summary(results)
    
    print("\n=== SARIF Parsing Results ===")
    print(f"Total findings: {summary['total']}")
    print(f"Files affected: {summary['files_affected']}")
    
    if summary['by_severity']:
        print("\nBy severity:")
        for severity, count in summary['by_severity'].items():
            print(f"  {severity}: {count}")
    
    if summary['by_rule']:
        print(f"\nTop rules (showing first 10):")
        sorted_rules = sorted(summary['by_rule'].items(), key=lambda x: x[1], reverse=True)
        for rule_id, count in sorted_rules[:10]:
            print(f"  {rule_id}: {count}")
    
    # Output as JSON for workflow consumption
    output = {
        'results': results,
        'summary': summary
    }
    
    with open('sarif_parsed_results.json', 'w') as f:
        json.dump(output, f, indent=2)
    
    print(f"\nDetailed results saved to: sarif_parsed_results.json")


if __name__ == "__main__":
    main()